In [1]:
import sqlite3
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
con = sqlite3.connect('take.db')

In [3]:
tiles = pd.read_sql_query("SELECT * FROM cv_piece_raw", con)

In [4]:
tiles.set_index(["episode_id", "id"])

                             r           g           b           h  \
episode_id id
r2.10      tile-13  143.137517  244.644860   11.174232   42.626836
           tile-7    11.154438  241.869822  111.375740   72.049704
           tile-5    11.483669  240.073662  110.711605   71.376650
           tile-4    11.179123  143.223595  244.788758  102.109327
           tile-9    11.769231  240.940760  111.261715   71.386384
...                        ...         ...         ...         ...
r7.185     tile-9   209.852704  111.917961    0.000000   15.846489
           tile-0   111.957270    0.000000  209.921556  133.830995
           tile-3   112.336411    0.000000  210.643393  134.426428
           tile-2   111.631961    0.000000  209.305690  133.694915
           tile-10  142.233645  133.845483  125.357009   15.000623

                             s           v  orientation        h_skew  \
episode_id id
r2.10      tile-13  241.875834  245.367156    32.541958  right-skewed
           tile-7   240.817160  242.338462    22.245955     symmetric
           tile-5   238.566366  240.884642     6.379068   left-skewed
           tile-4   241.885732  245.515133    30.315793  right-skewed
           tile-9   238.613616  242.626879    21.377890  right-skewed
...                        ...         ...          ...           ...
r7.185     tile-9   252.622747  210.083903    22.874797  right-skewed
           tile-0   250.934311  209.051020   -19.253908  right-skewed
           tile-3   252.057126  209.913445    -6.028783  right-skewed
           tile-2   250.677966  208.504237   -16.385460  right-skewed
           tile-10   29.817445  141.378816     4.933260  right-skewed

                           v_skew  num_edges       position       pos_x  \
episode_id id
r2.10      tile-13      symmetric          6    left center   59.333333
           tile-7   bottom-skewed          8  center center  141.666667
           tile-5   bottom-skewed          9    left center  101.666667
           tile-4       symmetric          6   right center  534.333333
           tile-9       symmetric          6    left center   99.000000
...                           ...        ...            ...         ...
r7.185     tile-9      top-skewed          6   right center  534.666667
           tile-0       symmetric          8      right top  501.333333
           tile-3       symmetric          8       left top  102.000000
           tile-2       symmetric          8      right top  578.000000
           tile-10  bottom-skewed          6      right top  577.000000

                         pos_y
episode_id id
r2.10      tile-13   73.777778
           tile-7    72.444444
           tile-5    80.444444
           tile-4   124.888889
           tile-9   178.666667
...                        ...
r7.185     tile-9   180.888889
           tile-0   327.555556
           tile-3   326.666667
           tile-2   378.666667
           tile-10  428.000000

[15762 rows x 13 columns]

In [5]:
referent = pd.read_sql_query("SELECT * FROM referent", con)
referent

     episode_id   object
0        r6.163   tile-0
1        r6.162   tile-1
2        r6.161   tile-6
3        r6.160   tile-1
4        r6.165  tile-11
...         ...      ...
1044      r7.80   tile-3
1045     r7.149  tile-11
1046     r6.159  tile-11
1047     r7.170  tile-11
1048      r7.72   tile-3

[1049 rows x 2 columns]

In [6]:
 new_query = '''
SELECT tiles.* FROM
tiles
INNER JOIN
referent
ON referent.object = tiles.id;
'''

In [7]:
words = pd.read_sql_query("SELECT * FROM hand", con)
words

      episode_id  inc   word  start_time  end_time
0         r6.163    1   dann        0.07      0.68
1         r6.163    2  <sil>        0.68      1.68
2         r6.163    3  <sil>        1.68      1.78
3         r6.163    4    aus        1.78      2.06
4         r6.163    5    der        2.06      2.24
...          ...  ...    ...         ...       ...
13858      r7.72    5  <sil>        1.09      1.67
13859      r7.72    6  <sil>        2.25      4.00
13860      r7.72    7  <sil>        4.00      4.20
13861      r7.72    8   okay        4.20      4.60
13862      r7.72    9  <sil>        4.60      4.66

[13863 rows x 5 columns]

In [11]:
#words.query('word == "rot"').mean()
rot = words[words.word == 'rot']
#column r value merge episode id with this data set and the tiles data set to create a smaller data set
tiles.merge(rot, left_on = 'episode_id', right_on = 'episode_id')

,episode_id,id,r,g,b,h,s,v,orientation,h_skew,v_skew,num_edges,position,pos_x,pos_y,inc,word,start_time,end_time
0,r1.96,tile-10,0.291667,195.275884,244.011995,95.000000,252.659091,244.757576,34.350817,right-skewed,symmetric,6,right center,534.000000,73.777778,4,rot,1.58,1.84
1,r1.96,tile-13,244.312676,0.243380,195.450141,154.582535,253.027042,244.890141,33.799694,right-skewed,symmetric,6,right center,572.000000,73.333333,4,rot,1.58,1.84
2,r1.96,tile-1,192.635628,240.486505,0.619433,35.074224,248.188934,239.807018,2.718309,symmetric,symmetric,12,right center,500.000000,75.555556,4,rot,1.58,1.84
3,r1.96,tile-12,0.588235,193.152941,241.290196,93.584314,249.345098,240.948459,-11.000379,symmetric,symmetric,10,left center,63.000000,76.000000,4,rot,1.58,1.84
4,r1.96,tile-8,50.180744,0.361488,243.772593,124.675724,252.688128,244.702304,-44.971472,right-skewed,top-skewed,6,right center,533.000000,122.666667,4,rot,1.58,1.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,r5.60,tile-0,232.619948,26.478934,225.381771,147.364574,220.551161,234.040413,15.889656,right-skewed,top-skewed,6,right top,499.333333,388.888889,4,rot,2.50,2.85
536,r5.60,tile-7,235.624287,34.164629,26.788916,0.984515,223.056235,235.675632,-14.275210,symmetric,bottom-skewed,7,right top,540.333333,430.666667,4,rot,2.50,2.85
537,r5.60,tile-11,238.753324,34.602394,27.152261,0.989362,224.045213,238.557846,0.899821,symmetric,bottom-skewed,6,left top,64.000000,428.444444,4,rot,2.50,2.85
538,r5.60,tile-14,27.070218,230.621065,238.041768,88.963075,220.938862,235.745763,-6.057203,symmetric,symmetric,12,right top,500.000000,430.666667,4,rot,2.50,2.85
539,r5.60,tile-12,34.033140,26.703397,234.690969,117.787075,220.014085,234.219553,29.813250,right-skewed,symmetric,7,left top,105.000000,433.777778,4,rot,2.50,2.85

In [18]:
links = words[words.word == 'links']
merge_links = tiles.merge(links, left_on = 'episode_id', right_on = 'episode_id')
merge_links

,episode_id,id,r,g,b,h,s,v,orientation,h_skew,v_skew,num_edges,position,pos_x,pos_y,inc,word,start_time,end_time
0,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,41,links,27.46,27.79
1,r2.10,tile-7,11.154438,241.869822,111.375740,72.049704,240.817160,242.338462,22.245955,symmetric,bottom-skewed,8,center center,141.666667,72.444444,41,links,27.46,27.79
2,r2.10,tile-5,11.483669,240.073662,110.711605,71.376650,238.566366,240.884642,6.379068,left-skewed,bottom-skewed,9,left center,101.666667,80.444444,41,links,27.46,27.79
3,r2.10,tile-4,11.179123,143.223595,244.788758,102.109327,241.885732,245.515133,30.315793,right-skewed,symmetric,6,right center,534.333333,124.888889,41,links,27.46,27.79
4,r2.10,tile-9,11.769231,240.940760,111.261715,71.386384,238.613616,242.626879,21.377890,right-skewed,symmetric,6,left center,99.000000,178.666667,41,links,27.46,27.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6879,r7.160,tile-6,196.712589,143.032660,143.032660,0.000000,69.919834,194.568290,-41.675106,left-skewed,symmetric,10,center top,138.666667,380.888889,2,links,0.35,0.58
6880,r7.160,tile-9,0.629371,95.257964,237.351981,105.566434,250.741259,238.967366,15.128424,right-skewed,top-skewed,6,right top,575.000000,388.444444,2,links,0.35,0.58
6881,r7.160,tile-14,242.814375,145.719375,0.162500,17.831250,253.228125,243.205625,44.380128,right-skewed,top-skewed,6,right top,571.000000,426.666667,2,links,0.35,0.58
6882,r7.160,tile-5,241.338848,0.171569,0.171569,0.000000,251.873162,240.946691,20.795702,symmetric,bottom-skewed,8,right top,501.666667,425.777778,2,links,0.35,0.58
6883,r7.160,tile-11,0.263672,96.235677,240.195964,105.960938,251.431641,239.929688,36.366493,symmetric,symmetric,8,left top,63.333333,430.666667,2,links,0.35,0.58

In [22]:
mean_links = merge_links['pos_x'].mean()
print("The average of positon x for the word links is " + str(mean_links))

The average of positon x for the word links is 318.0976176641477

In [26]:
not_links = words[words.word != 'links']
merge_values = tiles.merge(not_links, left_on = 'episode_id', right_on = 'episode_id')
merge_values

,episode_id,id,r,g,b,h,s,v,orientation,h_skew,v_skew,num_edges,position,pos_x,pos_y,inc,word,start_time,end_time
0,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,1,das,0.26,0.52
1,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,2,nÃ¤chste,0.52,0.98
2,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,3,ist,0.98,1.22
3,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,4,ein,1.22,1.37
4,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,5,<sil>,1.37,1.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201259,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,4,graue,0.67,1.00
201260,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,5,<sil>,1.00,2.30
201261,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,6,<sil>,2.30,3.15
201262,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,7,okay,3.15,3.40
201263,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,8,<sil>,3.40,3.45

In [30]:
mean_notlinks = merge_values['pos_x'].mean()
mean_notlinks
print("The average postion x of values that are not the word link is: " + str(mean_notlinks))

The average postion x of values that are not the word link is: 317.3703460794473

The average for a value that is not the word links is a bit lower than the average for the word links

In [49]:
overall = len(words.word.unique())
print("There are " + str(overall) + " words in the set vocabulary")

There are 383 words in the set vocabulary

In [50]:
words.groupby(['word']).size()

word
<sil>           4835
aber               4
ah                 2
aha                8
aham               1
                ...
Ã¤uÃŸere             1
Ã¤uÃŸerste           1
Ã¶h                 1
Ã¼ber               1
Ã¼bereinander       1
Length: 383, dtype: int64

In [65]:
mal = words[words.word == 'mal']
mal_values = tiles.merge(not_links, left_on = 'episode_id', right_on = 'episode_id')
mal_values

,episode_id,id,r,g,b,h,s,v,orientation,h_skew,v_skew,num_edges,position,pos_x,pos_y,inc,word,start_time,end_time
0,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,1,das,0.26,0.52
1,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,2,nÃ¤chste,0.52,0.98
2,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,3,ist,0.98,1.22
3,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,4,ein,1.22,1.37
4,r2.10,tile-13,143.137517,244.644860,11.174232,42.626836,241.875834,245.367156,32.541958,right-skewed,symmetric,6,left center,59.333333,73.777778,5,<sil>,1.37,1.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201259,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,4,graue,0.67,1.00
201260,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,5,<sil>,1.00,2.30
201261,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,6,<sil>,2.30,3.15
201262,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,7,okay,3.15,3.40
201263,r7.185,tile-10,142.233645,133.845483,125.357009,15.000623,29.817445,141.378816,4.933260,right-skewed,bottom-skewed,6,right top,577.000000,428.000000,8,<sil>,3.40,3.45

In [63]:
mean_mal_start_time = merge_values['start_time'].mean()
print("Average start time: " + str(mean_mal_start_time))
mean_mal_end_time = merge_values['end_time'].mean()
print("Average end time: " + str(mean_mal_end_time))
print("Average of both averages combined: " + str(mean_mal_start_time + mean_mal_end_time / 2))

Average start time: 4.8917915772312375
Average end time: 5.493661658319671
Average of both averages combined: 7.6386224063910735

I had the assumption that the word 'mal' meant time becasue when I found all the episodes where it appeared it was connected to the start and end times. Then I didn't know which column I wanted to average/find the mean so I did both the start and end times. Then I took both of those means added them together then took the mean of that. So, my assumptions were correct about what mal meant in correlation to the data set